CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_low_id BIGINT NOT NULL,
    member_high_id BIGINT NOT NULL,
    low_last_read_id BIGINT NOT NULL DEFAULT 0,
    high_last_read_id BIGINT NOT NULL DEFAULT 0,
    last_message_id BIGINT,
    last_message_content VARCHAR(2000),
    last_message_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_chat_room_members UNIQUE (member_low_id, member_high_id),
    CONSTRAINT ck_chat_room_members CHECK (member_low_id < member_high_id)
);
CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES chat_rooms(id),
    sender_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    client_message_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_chat_message_client UNIQUE (room_id, sender_id, client_message_id)
);
CREATE INDEX ix_chat_room_low ON chat_rooms(member_low_id, updated_at DESC, id DESC);
CREATE INDEX ix_chat_room_high ON chat_rooms(member_high_id, updated_at DESC, id DESC);
CREATE INDEX ix_chat_message_history ON chat_messages(room_id, id DESC);
CREATE INDEX ix_chat_message_sender_time ON chat_messages(sender_id, created_at);
