CREATE TABLE members (
                         member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email VARCHAR(255) NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         nickname VARCHAR(50) NOT NULL,
                         profile_image_key TEXT,
                         created_at TIMESTAMP(6),
                         updated_at TIMESTAMP(6),

                         CONSTRAINT uk_members_email
                             UNIQUE (email),

                         CONSTRAINT uk_members_nickname
                             UNIQUE (nickname)
);


CREATE TABLE refresh_tokens (
                                refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                member_id BIGINT NOT NULL,
                                refresh_token VARCHAR(500) NOT NULL,
                                expires_at TIMESTAMP(6),
                                created_at TIMESTAMP(6) NOT NULL
);


CREATE TABLE friendships (
                             friendship_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             requester_id BIGINT NOT NULL,
                             addressee_id BIGINT NOT NULL,
                             status VARCHAR(20) NOT NULL,
                             created_at TIMESTAMP(6),
                             updated_at TIMESTAMP(6),

                             CONSTRAINT friendships_status_check
                                 CHECK (
                                     status IN (
                                                'PENDING',
                                                'ACCEPTED',
                                                'REJECTED',
                                                'CANCELLED'
                                         )
                                     )
);


CREATE TABLE markets (
                         market_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         host_id BIGINT NOT NULL,
                         title VARCHAR(100) NOT NULL,
                         description TEXT,
                         invite_code VARCHAR(100) NOT NULL,
                         cover_image_url TEXT,
                         created_at TIMESTAMP(6),
                         updated_at TIMESTAMP(6),

                         CONSTRAINT uk_markets_invite_code
                             UNIQUE (invite_code),

                         CONSTRAINT fk_markets_host
                             FOREIGN KEY (host_id)
                                 REFERENCES members (member_id)
);


CREATE TABLE market_members (
                                market_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                market_id BIGINT NOT NULL,
                                member_id BIGINT NOT NULL,
                                joined_at TIMESTAMP(6) NOT NULL,

                                CONSTRAINT uk_market_member
                                    UNIQUE (market_id, member_id),

                                CONSTRAINT fk_market_members_market
                                    FOREIGN KEY (market_id)
                                        REFERENCES markets (market_id),

                                CONSTRAINT fk_market_members_member
                                    FOREIGN KEY (member_id)
                                        REFERENCES members (member_id)
);


CREATE TABLE collection_items (
                                  collection_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  member_id BIGINT NOT NULL,
                                  title VARCHAR(150) NOT NULL,
                                  description TEXT,
                                  image_url TEXT,
                                  is_public BOOLEAN NOT NULL,
                                  created_at TIMESTAMP(6),
                                  updated_at TIMESTAMP(6),

                                  CONSTRAINT fk_collection_items_member
                                      FOREIGN KEY (member_id)
                                          REFERENCES members (member_id)
);


CREATE TABLE items (
                       item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       market_id BIGINT NOT NULL,
                       collection_item_id BIGINT,
                       seller_id BIGINT NOT NULL,
                       title VARCHAR(150),
                       description TEXT,
                       trade_type VARCHAR(20) NOT NULL,
                       price BIGINT,
                       status VARCHAR(20) NOT NULL,
                       image_key VARCHAR(255),
                       created_at TIMESTAMP(6),
                       updated_at TIMESTAMP(6),

                       CONSTRAINT ck_items_trade_type
                           CHECK (
                               trade_type IN (
                                              'SALE',
                                              'GIVEAWAY',
                                              'RENTAL'
                                   )
                               ),

                       CONSTRAINT ck_items_status
                           CHECK (
                               status IN (
                                          'AVAILABLE',
                                          'IN_PROGRESS',
                                          'COMPLETED'
                                   )
                               ),

                       CONSTRAINT fk_items_market
                           FOREIGN KEY (market_id)
                               REFERENCES markets (market_id),

                       CONSTRAINT fk_items_collection_item
                           FOREIGN KEY (collection_item_id)
                               REFERENCES collection_items (collection_item_id),

                       CONSTRAINT fk_items_seller
                           FOREIGN KEY (seller_id)
                               REFERENCES members (member_id)
);


CREATE TABLE beg_requests (
                              beg_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              collection_item_id BIGINT NOT NULL,
                              applicant_id BIGINT NOT NULL,
                              story TEXT,
                              status VARCHAR(20) NOT NULL,
                              created_at TIMESTAMP(6),
                              updated_at TIMESTAMP(6),

                              CONSTRAINT ck_beg_requests_status
                                  CHECK (
                                      status IN (
                                                 'PENDING',
                                                 'ACCEPTED',
                                                 'REJECTED'
                                          )
                                      )
);


CREATE TABLE notifications (
                               notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               receiver_id BIGINT NOT NULL,
                               type VARCHAR(30) NOT NULL,
                               message TEXT NOT NULL,
                               is_read BOOLEAN NOT NULL,
                               reference_type VARCHAR(30) NOT NULL,
                               reference_id BIGINT NOT NULL,
                               created_at TIMESTAMP(6) NOT NULL,
                               updated_at TIMESTAMP(6),

                               CONSTRAINT ck_notifications_type
                                   CHECK (
                                       type IN (
                                                'TRADE_REQUESTED',
                                                'TRADE_ACCEPTED',
                                                'TRADE_REJECTED',
                                                'TRADE_CANCELLED',
                                                'TRADE_COMPLETION_CONFIRMED',
                                                'TRADE_COMPLETED',
                                                'FRIEND_REQUESTED',
                                                'FRIEND_ACCEPTED'
                                           )
                                       ),

                               CONSTRAINT ck_notifications_reference_type
                                   CHECK (
                                       reference_type IN (
                                                          'ITEM_TRADE_REQUEST',
                                                          'COLLECTION_TRADE_REQUEST',
                                                          'BEG_REQUEST',
                                                          'FRIEND_REQUEST'
                                           )
                                       ),

                               CONSTRAINT fk_notifications_receiver
                                   FOREIGN KEY (receiver_id)
                                       REFERENCES members (member_id)
);


CREATE TABLE trade_requests (
                                trade_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                item_id BIGINT NOT NULL,
                                requester_id BIGINT NOT NULL,
                                rental_start_date DATE,
                                rental_end_date DATE,
                                status VARCHAR(20) NOT NULL,
                                requester_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
                                message TEXT,
                                created_at TIMESTAMP(6),
                                updated_at TIMESTAMP(6),

                                CONSTRAINT ck_trade_requests_status
                                    CHECK (
                                        status IN (
                                                   'PENDING',
                                                   'ACCEPTED',
                                                   'REJECTED',
                                                   'CANCELLED',
                                                   'COMPLETED'
                                            )
                                        ),

                                CONSTRAINT fk_trade_requests_item
                                    FOREIGN KEY (item_id)
                                        REFERENCES items (item_id),

                                CONSTRAINT fk_trade_requests_requester
                                    FOREIGN KEY (requester_id)
                                        REFERENCES members (member_id)
);


CREATE UNIQUE INDEX uk_trade_requests_pending
    ON trade_requests (item_id, requester_id)
    WHERE status = 'PENDING';


CREATE TABLE collection_trade_requests (
                                           collection_trade_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           collection_item_id BIGINT NOT NULL,
                                           requester_id BIGINT NOT NULL,
                                           offer_collection_item_id BIGINT,
                                           trade_type VARCHAR(20),
                                           status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                           requester_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
                                           owner_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
                                           created_at TIMESTAMP(6),
                                           updated_at TIMESTAMP(6),

                                           CONSTRAINT ck_collection_trade_requests_trade_type
                                               CHECK (
                                                   trade_type IN (
                                                                  'RENTAL',
                                                                  'EXCHANGE'
                                                       )
                                                   )
);


CREATE TABLE trades (
                        trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        collection_trade_request_id BIGINT,
                        trade_request_id BIGINT,
                        item_id BIGINT,
                        buyer_id BIGINT NOT NULL,
                        seller_id BIGINT NOT NULL,
                        completed_at TIMESTAMP(6),
                        created_at TIMESTAMP(6) NOT NULL
);