CREATE TABLE member_pokes (
    poke_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_member_pokes_sender FOREIGN KEY (sender_id)
        REFERENCES members (member_id) ON DELETE CASCADE,
    CONSTRAINT fk_member_pokes_recipient FOREIGN KEY (recipient_id)
        REFERENCES members (member_id) ON DELETE CASCADE,
    CONSTRAINT ck_member_pokes_not_self CHECK (sender_id <> recipient_id)
);

CREATE INDEX idx_member_pokes_recipient_created
    ON member_pokes (recipient_id, created_at DESC);
